In [1]:
# TODO: For amounts calculate the confidence intervals for transactions above the average for a particular date.
# TODO: For the location calculate the fraud rate per 100k
# TODO: Risk rate for location
# TODO: Factor in for seasonality

In [2]:
# Import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so
import datetime as dt
from datetime import datetime
import os
# Change directory to the data location
os.chdir('../../ml_data')

In [3]:


# Read the data
df = pd.read_csv('credit_card_fraud_dataset.csv')

# Parameters
bandwidth_plus = 1.10
bandwidth_minus = 0.90

In [4]:
df.head()

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0

In [5]:
df["Year"] =(df["TransactionDate"].astype(str).str.split(" ").str[0]).str.split('-').str[0]
df["Month"]=(df["TransactionDate"].astype(str).str.split(" ").str[0]).str.split('-').str[1]
df["Day"]=(df["TransactionDate"].astype(str).str.split(" ").str[0]).str.split('-').str[2]
df["Year-Month"] = df["Year"]+'-'+df["Month"]

In [6]:
monay_mean = df[["Amount", "Year-Month"]]
monay_mean= monay_mean.rename(columns={'Amount':'Mean'})
monay_mean = monay_mean.groupby(by=['Year-Month']).mean().reset_index()
monay_mean

   Year-Month         Mean
0     2023-10  2473.868349
1     2023-11  2460.981078
2     2023-12  2511.422951
3     2024-01  2496.120104
4     2024-02  2493.052607
5     2024-03  2516.489406
6     2024-04  2480.872180
7     2024-05  2500.726202
8     2024-06  2468.091999
9     2024-07  2508.055940
10    2024-08  2500.567465
11    2024-09  2522.515053
12    2024-10  2518.399717

In [7]:
df = pd.merge(df, monay_mean, on='Year-Month')
df.head()

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud,Year,Month,Day,Year-Month,Mean
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0,2024,04,03,2024-04,2480.872180
1,2,2024-03-19 13:20:35.462824,2659.71,109,refund,Dallas,0,2024,03,19,2024-03,2516.489406
2,3,2024-01-08 10:08:35.462834,784.00,394,purchase,New York,0,2024,01,08,2024-01,2496.120104
3,4,2024-04-13 23:50:35.462850,3514.40,944,purchase,Philadelphia,0,2024,04,13,2024-04,2480.872180
4,5,2024-07-12 18:51:35.462858,369.07,475,purchase,Phoenix,0,2024,07,12,2024-07,2508.055940

In [8]:
df['Mean_p_ten'] = df["Mean"]*bandwidth_plus
df['Mean_m_ten'] = df["Mean"]*bandwidth_minus